// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegundaEvaluacion.Shared.Datos.Entidades;

namespace SegundaEvaluacion.Shared.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SegundaEvaluacion.Shared.Datos.Entidades.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodPais")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("Personadni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Personadni");

                    b.HasIndex(new[] { "CodPais" }, "UQ_Pais_Cod")
                        .IsUnique();

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("SegundaEvaluacion.Shared.Datos.Entidades.Persona", b =>
                {
                    b.Property<int>("dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("dni");

                    b.HasIndex(new[] { "dni" }, "UQ_dni")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("SegundaEvaluacion.Shared.Datos.Entidades.Pais", b =>
                {
                    b.HasOne("SegundaEvaluacion.Shared.Datos.Entidades.Persona", null)
                        .WithMany("Paises")
                        .HasForeignKey("Personadni");
                });

            modelBuilder.Entity("SegundaEvaluacion.Shared.Datos.Entidades.Persona", b =>
                {
                    b.Navigation("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
